name=BajaCAN
version=2.2.3
author=NJIT Highlander Racing
maintainer=NJIT Highlander Racing, baja@njit.edu
sentence=Consolidated implementation of NJIT Highlander Racing's CAN Bus implementation and message id allocation.
paragraph=This library was designed for use with ESP-32 modules. It may work with similar microcontrollers, but this is neither supported nor tested.
category=Communication
url=https://github.com/NJIT-Highlander-Racing-Electrical/CAN-Bus
architectures=*
includes=BajaCAN.h
